[project]
name = "bugreport"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "adbc-driver-manager>=1.9.0",
    "adbc-driver-postgresql>=1.9.0",
    "pyarrow>=22.0.0",
]
